Testing multistage

diff --git a/.github/workflows/docker-windows-workflow.yml b/.github/workflows/docker-windows-workflow.yml
--- a/.github/workflows/docker-windows-workflow.yml
+++ b/.github/workflows/docker-windows-workflow.yml
@@ -22,12 +22,22 @@ jobs:
     - name: Build Docker image
       shell: bash
       run: |
+        echo "Login to Github Package Registry"
         echo ${{ secrets.GITHUB_TOKEN }} | \
           docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
-        docker pull $IMAGE_NAME || true
+
+        echo "Pull previously build buildtools stage image (missing image is ok)"
         docker pull $BUILDTOOLS_NAME || true
+
+        echo "Pull previously build final stage image (missing image is ok)"
+        docker pull $IMAGE_NAME || true
+
+        echo "Build and push buildtools stage"
         docker build -t $BUILDTOOLS_NAME --cache-from $BUILDTOOLS_NAME --target buildtools docker/windows
+        docker history $BUILDTOOLS_NAME
+        docker push $BUILDTOOLS_NAME
+
+        echo "Build and push final stage"
         docker build -t $IMAGE_NAME --cache-from $BUILDTOOLS_NAME,$IMAGE_NAME docker/windows
         docker history $IMAGE_NAME
-        docker push $BUILDTOOLS_NAME
         docker push $IMAGE_NAME
